name: Update Recent Activity

on:
  schedule:
    - cron: "*/30 * * * *" # se ejecuta cada 30 minutos
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JamesIves/github-activity-readme@v0.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "🔄 Actualizando últimos commits automáticamente"
