name: Update Recent Activity

on:
  schedule:
    - cron: "*/10 * * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Activity (Readme-Workflows)
        uses: Readme-Workflows/recent-activity@v2
        with:
          GH_USERNAME: ${{ github.repository_owner }}
          MAX_LINES: 6
          COMMIT_MSG: "🔄 Actualizando últimos commits automáticamente"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
